### Regularización en Keras

In [1]:
from IPython.display import Image


import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (7, 7)

# Cargamos los datos

En deep learning no se suele hacer validación cruzada (a menos que el tamaño del dataset y el tiempo de entrenamiento lo permita). En lugar de eso se hacen simples separaciónes entre datos de entrenamiento y de validación.

In [2]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 3s 0us/step


In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
x_train[0].shape

(28, 28)

In [5]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
from ipywidgets import interact, IntSlider

In [7]:
@interact(i=IntSlider(min=0,max=50,step=1,value=1))
def dibujar_numero(i):
    plt.imshow(x_train[i], cmap="gray")
    plt.title("Número {}".format(y_train[i]))

interactive(children=(IntSlider(value=1, description='i', max=50), Output()), _dom_classes=('widget-interact',…

In [8]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten

In [9]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [10]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [11]:
x_train[0].shape

(28, 28)

In [12]:
x_train_plano = x_train.reshape(x_train.shape[0],28*28)
x_test_plano = x_test.reshape(x_test.shape[0],28*28)

In [13]:
x_train_plano[0].shape

(784,)

In [14]:
x_train_plano[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [15]:
from keras.utils.np_utils import to_categorical

In [16]:
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [17]:
y_train_one_hot = to_categorical(y_train)
y_test_one_hot = to_categorical(y_test)

In [18]:
y_train_one_hot[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [19]:
modelo = Sequential()
modelo.add(Dense(50, activation="relu", input_shape=(784,)))
modelo.add(Dense(250, activation="relu"))
modelo.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                39250     
_________________________________________________________________
dense_1 (Dense)              (None, 250)               12750     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                2510      
Total params: 54,510
Trainable params: 54,510
Non-trainable params: 0
_________________________________________________________________


In [20]:
modelo.fit(x_train_plano, y_train_one_hot, epochs=50, batch_size=1000, verbose=0);

Vamos a ver ahora como se compara el funcionamiento del modelo respecto a los datos de entrenamiento y los de test. 

In [21]:
RESULTADOS = {}

In [22]:
modelo.metrics_names

['loss', 'accuracy']

In [23]:
evaluacion_train = modelo.evaluate(x_train_plano, y_train_one_hot)
evaluacion_train

1875/1875 [==============================] - 1s 643us/step - loss: 2.3011 - accuracy: 0.1124


[2.301074981689453, 0.11236666887998581]

In [24]:
evaluacion_test = modelo.evaluate(x_test_plano, y_test_one_hot)
evaluacion_test

313/313 [==============================] - 0s 940us/step - loss: 2.3025 - accuracy: 0.1133


[2.302511215209961, 0.11330000311136246]

In [25]:
RESULTADOS["sin_regularizacion"] = [evaluacion_train[1], evaluacion_test[1]]

### Regularización l1, o l2

Keras permite regularizar los pesos, los sesgos (bias) y las activaciones de  forma independiente, pasando el parámetro `kernel_regularizer`, `bias_regularizer` y `activity_regularizer` respectivamente.

Keras tiene los penalizadores `l1`, `l2` y `l1_l2` (elasticnet)

In [26]:
from keras import regularizers

modelo_l2 = Sequential()
modelo_l2.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_l2.add(Dense(250, activation="relu", kernel_regularizer=regularizers.l2(0.01)))
modelo_l2.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_l2.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_l2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_4 (Dense)              (None, 250)               12750     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                2510      
Total params: 54,510
Trainable params: 54,510
Non-trainable params: 0
_________________________________________________________________


In [27]:
modelo_l2.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000);

In [28]:
acc_train = modelo_l2.evaluate(x_train_plano, y_train_one_hot)[1]
acc_train

1875/1875 [==============================] - 1s 683us/step - loss: 1.7781 - accuracy: 0.6439


0.6438999772071838

In [29]:
acc_test = modelo.evaluate(x_test_plano, y_test_one_hot)[1]
acc_test

313/313 [==============================] - 0s 1ms/step - loss: 2.3025 - accuracy: 0.1133


0.11330000311136246

In [30]:
RESULTADOS["regularizacion_l2"] = [acc_train, acc_test]

Hacemos lo mismo pero con regularización l1

In [31]:
modelo_l1 = Sequential()
modelo_l1.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_l1.add(Dense(250, activation="relu", kernel_regularizer=regularizers.l1(0.01)))
modelo_l1.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_l1.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_l1.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000)

acc_train = modelo_l1.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_l1.evaluate(x_test_plano, y_test_one_hot)[1]

RESULTADOS["regularizacion_l1"] = [acc_train, acc_test]

313/313 [==============================] - 0s 956us/step - loss: 5.7015 - accuracy: 0.1135


In [32]:
print(acc_train, acc_test)

0.11236666887998581 0.11349999904632568


### Dropout

Ahora vamos a añadir Dropout a la misma red. Dropout simplemente ignora un porcentaje `p` de las unidades (neuronas) en cada iteración del entrenamiento (forward prop y backprop)

In [33]:
from keras.layers import Dropout

In [34]:
modelo_dropout = Sequential()
modelo_dropout.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_dropout.add(Dense(250, activation="relu"))
modelo_dropout.add(Dropout(0.2))
modelo_dropout.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_dropout.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_dropout.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_10 (Dense)             (None, 250)               12750     
_________________________________________________________________
dropout (Dropout)            (None, 250)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 10)                2510      
Total params: 54,510
Trainable params: 54,510
Non-trainable params: 0
_________________________________________________________________


Vemos que el número de parámetros a entrenar es el mismo, Dropout no añade pesos a la red

In [35]:
modelo_dropout.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000);

In [36]:
acc_train = modelo_dropout.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_dropout.evaluate(x_test_plano, y_test_one_hot)[1]

313/313 [==============================] - 0s 965us/step - loss: 1.5857 - accuracy: 0.3761


In [37]:
print(acc_train, acc_test)

0.37146666646003723 0.37610000371932983


In [38]:
RESULTADOS["regularizacion_dropout"] = [acc_train, acc_test]

### Normalización en bloques (batch normalization)

In [39]:
from keras.layers import BatchNormalization

In [40]:
modelo_bnorm = Sequential()
modelo_bnorm.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_bnorm.add(Dense(250, activation="relu"))
modelo_bnorm.add(BatchNormalization())
modelo_bnorm.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_bnorm.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_bnorm.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 50)                39250     
_________________________________________________________________
dense_13 (Dense)             (None, 250)               12750     
_________________________________________________________________
batch_normalization (BatchNo (None, 250)               1000      
_________________________________________________________________
dense_14 (Dense)             (None, 10)                2510      
Total params: 55,510
Trainable params: 55,010
Non-trainable params: 500
_________________________________________________________________


In [41]:
modelo_bnorm.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000)
acc_train = modelo_bnorm.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_bnorm.evaluate(x_test_plano, y_test_one_hot)[1]

RESULTADOS["batch_normalization"] = [acc_train, acc_test]
print(acc_train, acc_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.1426 - accuracy: 0.9591
0.9663500189781189 0.9591000080108643


### Batch Normalization + Dropout

Una práctica común es poner normalizacion batch y dropout juntos en una capa

In [42]:
modelo_bnorm_drop = Sequential()
modelo_bnorm_drop.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_bnorm_drop.add(Dense(250, activation="relu"))
modelo_bnorm_drop.add(BatchNormalization())
modelo_bnorm_drop.add(Dropout(0.2))
modelo_bnorm_drop.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_bnorm_drop.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_bnorm_drop.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000)
acc_train = modelo_bnorm_drop.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_bnorm_drop.evaluate(x_test_plano, y_test_one_hot)[1]

RESULTADOS["batch_normalization + dropout"] = [acc_train, acc_test]
print(acc_train, acc_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.1408 - accuracy: 0.9570
0.9649166464805603 0.9570000171661377


Ahora metemos los resultados en un dataframe para inspeccionarlos

In [43]:
import pandas as pd

resultados = pd.DataFrame(RESULTADOS).T
resultados.columns = ["acc_train", "acc_test"]
resultados["pct_diff"] = 1 - (resultados.acc_test / resultados.acc_train)

In [44]:
resultados.sort_values(by="pct_diff")

acc_train  acc_test  pct_diff
regularizacion_dropout          0.371467    0.3761 -0.012473
regularizacion_l1               0.112367    0.1135 -0.010086
sin_regularizacion              0.112367    0.1133 -0.008306
batch_normalization             0.966350    0.9591  0.007502
batch_normalization + dropout   0.964917    0.9570  0.008204
regularizacion_l2               0.643900    0.1133  0.824041